Name: Shardul Pramod Karanjekar

Course: Mtech Data Science

Registration number: 24-27-16

Q1. a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange

In [1]:
import numpy as np
var1 = np.arange(0,30)
print(var1,var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,)


Q1. b) Change var1 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [2]:
var2 = var1.reshape((5,6))
print(var2,var2.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6)


Q1. c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

In [3]:
var3 = var1.reshape((2,3,5))
print(var3,var3.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (2, 3, 5)


Q1. d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

In [4]:
var2[1][0] = -1
print(var1,var2,var3)

[ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] [[[ 0  1  2  3  4]
  [ 5 -1  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Here elements of all the three variables changed because when we reshape var1 we are only getting a different view of the same array in var2 and var3. If we want it to not reflect the same changes then we need to create a copy of var1 and then reshape it.

Q1. e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
1. Sum var3 over its second dimension and print the result.
2. Sum var3 over its third dimension and print the result.
3.  Sum var3 over both its first and third dimensions and print the result.

In [5]:
np.sum(var3,axis=1)

array([[15, 11, 21, 24, 27],
       [60, 63, 66, 69, 72]])

In [6]:
np.sum(var3,axis=2)

array([[ 10,  28,  60],
       [ 85, 110, 135]])

In [7]:
np.sum(var3,axis = (0,2))

array([ 95, 138, 195])

Q1. f) Write code to do the following:
1. Slice out the second row of var2 and print it.
2. Slice out the last column of var2 using the -1 notation and print it.
3. Slice out the top right 2 × 2 submatrix of var2 and print it.

In [8]:
print(var2[1][:])
print(var2[-4][:])
print(var2[:2,-2:])

[-1  7  8  9 10 11]
[-1  7  8  9 10 11]
[[ 4  5]
 [10 11]]


Q2. a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [9]:
vector = np.arange(10) +1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


Q2. b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [10]:
row_vec = vector.reshape((1,10))
col_vec = vector.reshape((10,1))

A = row_vec + col_vec
print(row_vec,col_vec,A)

[[ 1  2  3  4  5  6  7  8  9 10]] [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


Q2. c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
```
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

```



In [11]:
import numpy.random as npr
data = np.exp(npr.randn(50,5))

stdzed_data = (data - data.mean())/data.std()

print(stdzed_data)

[[-5.14698997e-01 -5.91141289e-01 -4.52882918e-01 -1.94022880e-01
  -4.75634851e-01]
 [ 1.17182120e+00 -4.21997623e-01 -6.09242086e-01 -2.79591577e-01
  -4.45825992e-01]
 [ 3.00122422e-01  9.74005435e-01 -5.94971634e-01 -6.02062649e-01
  -4.28489263e-01]
 [-6.41309128e-01  1.81980802e+00 -4.15444197e-01 -1.62772358e-02
  -4.10911209e-01]
 [-5.47366139e-01 -1.17351943e-01 -2.32623475e-01 -4.98065027e-01
  -4.14331354e-01]
 [-1.65741268e-01 -5.08763566e-01 -1.18512556e-01  1.52639371e+00
  -4.68488656e-01]
 [-6.52581634e-02  4.11059188e-02  7.03773151e-02 -1.75123652e-01
  -5.93309103e-01]
 [ 1.78804500e-01 -2.71025170e-01 -1.57651694e-01 -4.52624850e-01
  -6.52162658e-01]
 [-5.56914215e-01 -4.26486534e-01 -3.88025334e-01  5.41753117e-01
  -5.56571567e-01]
 [ 8.78708351e+00 -3.79220720e-01 -5.71784861e-01 -3.99963840e-01
  -6.22345787e-01]
 [ 1.82097228e-01  2.92680425e-01  1.42645203e+00  8.62400707e-01
   8.17724188e-01]
 [-3.60690611e-01  7.49011695e-01  1.89938852e+00  5.02413639e-01

Q2. d) You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal
distribution.

Q2. e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.

In [12]:
col_mean = data.mean(axis=0)
col_std = data.std(axis=0)
print(col_mean,col_std,sep="\n")

[2.09500978 1.52768225 1.81774565 2.09181764 1.49305673]
[3.5761338  1.73682264 2.21465087 2.85329873 1.84883311]


Q2. f) Now standardize the data matrix by
1. subtracting the mean off of each column,
and
2. dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized.

To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [13]:
normalized_data = (data-col_mean)/col_std

norm_mean = np.mean(normalized_data)
norm_std = np.std(normalized_data)
print(norm_mean,norm_std)

-1.5454304502782178e-16 1.0


Q3. a) Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
for
any N. Do it without using a loop. Here’s a stub to get you started:
```
def vandermonde (N):
    vec = np.arange (N) +1
    # write your code here .
```
Use your function for N = 12, store it in variable named vander, and print the
result.

In [14]:
np.vander([1,2,3,4],5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [15]:
def vandermonde(N):
    vec = np.arange(N) + 1

    vender = vec[:,np.newaxis]**np.arange(N)
    return vender

vander = vandermonde(12)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

Q3. b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.

In [16]:
x = np.ones(12)
b = np.matmul(vander,x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


Q3. c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.

In [17]:
from numpy.linalg import inv
i = np.dot(inv(vander),b)
print(i)

[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


Q3. d) Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?

In [18]:
ii = np.linalg.solve(vander,b)
print(ii)

[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


The solve method is generally more numerically stable and accurate than explicitly computing the inverse and multiplying. This is because solve uses more sophisticated algorithms (like LU decomposition) that are less prone to accumulation of floating-point errors.

# [Github](https://github.com/Devels-breath/Assign2_Shardul_16)